name: Project CI
run-name: ${{ github.actor }} is testing project with GitHub Actions 🚀
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  CI:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: eslint tests
        run: npm run lint
      - name: stylelint tests
        run: npm run style
      - name: unit tests
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: test screenshots
        run: npm run test:ui:static
